name: Compile Member Data

on:
  push:
    branches: [main]
    paths:
      - 'members/**'
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Compile member data
        run: |
          mkdir -p compiled-data
          cp -r members/* compiled-data/
          
      - name: Create all-members.json
        run: |
          node -e "
            const fs = require('fs');
            const path = require('path');
            
            const membersDir = path.join(process.cwd(), 'members');
            const memberFolders = fs.readdirSync(membersDir)
              .filter(file => fs.statSync(path.join(membersDir, file)).isDirectory());
            
            const allMembers = [];
            
            memberFolders.forEach(folder => {
              const infoPath = path.join(membersDir, folder, 'info.json');
              if (fs.existsSync(infoPath)) {
                const info = JSON.parse(fs.readFileSync(infoPath, 'utf8'));
                allMembers.push(info);
              }
            });
            
            fs.writeFileSync(
              path.join(process.cwd(), 'compiled-data', 'all-members.json'),
              JSON.stringify(allMembers, null, 2)
            );
            
            console.log('Created all-members.json with ' + allMembers.length + ' members');
          "
          
      - name: Commit compiled data
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add compiled-data/
          git commit -m "Update compiled member data" || echo "No changes to commit"
          git push
