name: Update Website Data

on:
  push:
    branches: [main]
    paths:
      - 'members/**'

jobs:
  update-website:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger website rebuild
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: your-org/tep-website
          event-type: member-data-updated
